CREATE DATABASE [dentiste_db2];
GO
USE [dentiste_db2];
GO

IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
CREATE TABLE [ACTE_MEDICAL] (
    [ACT_ID] int NOT NULL IDENTITY,
    [ACT_LIBELLE] nvarchar(100) NOT NULL,
    [ACT_TARIF_DE_BASE] decimal(18,2) NOT NULL,
    [ACT_CODE_NOMENCLATURE] nvarchar(max) NULL,
    CONSTRAINT [PK_ACTE_MEDICAL] PRIMARY KEY ([ACT_ID])
);

CREATE TABLE [AUDIT_LOG] (
    [AUD_ID] int NOT NULL IDENTITY,
    [AUD_ACTION] nvarchar(50) NOT NULL,
    [AUD_TABLE_NAME] nvarchar(100) NOT NULL,
    [AUD_TIMESTAMP] datetime2 NOT NULL,
    [AUD_USER_ID] nvarchar(max) NOT NULL,
    [AUD_KEY_VALUES] nvarchar(max) NULL,
    [AUD_OLD_VALUES] nvarchar(max) NULL,
    [AUD_NEW_VALUES] nvarchar(max) NULL,
    CONSTRAINT [PK_AUDIT_LOG] PRIMARY KEY ([AUD_ID])
);

CREATE TABLE [PATIENT] (
    [PAT_ID] int NOT NULL IDENTITY,
    [PAT_NOM] nvarchar(100) NOT NULL,
    [PAT_PRENOM] nvarchar(100) NOT NULL,
    [PAT_DATE_NAISSANCE] datetime2 NOT NULL,
    [PAT_TELEPHONE] nvarchar(20) NOT NULL,
    [PAT_EMAIL] nvarchar(max) NULL,
    [PAT_ADRESSE] nvarchar(max) NULL,
    [PAT_ANTECEDENTS_MEDICAUX] nvarchar(max) NULL,
    [PAT_GROUP_SANGUIN] nvarchar(max) NULL,
    [PAT_CREATED_AT] datetime2 NOT NULL,
    CONSTRAINT [PK_PATIENT] PRIMARY KEY ([PAT_ID])
);

CREATE TABLE [ROLE] (
    [ROL_ID] int NOT NULL IDENTITY,
    [ROL_NAME] nvarchar(30) NOT NULL,
    [ROL_DESCRIPTION] nvarchar(max) NULL,
    CONSTRAINT [PK_ROLE] PRIMARY KEY ([ROL_ID])
);

CREATE TABLE [FACTURE] (
    [FAC_ID] int NOT NULL IDENTITY,
    [FAC_NUMERO_FACTURE] nvarchar(20) NOT NULL,
    [FAC_DATE_EMISSION] datetime2 NOT NULL,
    [FAC_MONTANT_TOTAL] decimal(18,2) NOT NULL,
    [FAC_MONTANT_PAYE] decimal(18,2) NOT NULL,
    [FAC_STATUT_PAIEMENT] nvarchar(30) NOT NULL,
    [FAC_PATIENT_ID] int NOT NULL,
    CONSTRAINT [PK_FACTURE] PRIMARY KEY ([FAC_ID]),
    CONSTRAINT [FK_FACTURE_PATIENT_FAC_PATIENT_ID] FOREIGN KEY ([FAC_PATIENT_ID]) REFERENCES [PATIENT] ([PAT_ID]) ON DELETE NO ACTION
);

CREATE TABLE [USER] (
    [USR_ID] int NOT NULL IDENTITY,
    [USR_USERNAME] nvarchar(50) NOT NULL,
    [USR_EMAIL] nvarchar(100) NOT NULL,
    [USR_PASSWORD_HASH] nvarchar(255) NOT NULL,
    [USR_PASSWORD_SALT] nvarchar(255) NOT NULL,
    [USR_NOM] nvarchar(100) NOT NULL,
    [USR_PRENOM] nvarchar(100) NOT NULL,
    [USR_IS_ACTIVE] bit NOT NULL,
    [USR_CREATED_AT] datetime2 NOT NULL,
    [USR_ROLE_ID] int NOT NULL,
    CONSTRAINT [PK_USER] PRIMARY KEY ([USR_ID]),
    CONSTRAINT [FK_USER_ROLE_USR_ROLE_ID] FOREIGN KEY ([USR_ROLE_ID]) REFERENCES [ROLE] ([ROL_ID]) ON DELETE NO ACTION
);

CREATE TABLE [PAIEMENT] (
    [PAI_ID] int NOT NULL IDENTITY,
    [PAI_DATE_PAIEMENT] datetime2 NOT NULL,
    [PAI_MONTANT] decimal(18,2) NOT NULL,
    [PAI_MODE_PAIEMENT] nvarchar(30) NOT NULL,
    [PAI_FACTURE_ID] int NOT NULL,
    CONSTRAINT [PK_PAIEMENT] PRIMARY KEY ([PAI_ID]),
    CONSTRAINT [FK_PAIEMENT_FACTURE_PAI_FACTURE_ID] FOREIGN KEY ([PAI_FACTURE_ID]) REFERENCES [FACTURE] ([FAC_ID]) ON DELETE CASCADE
);

CREATE TABLE [CONSULTATION] (
    [CON_ID] int NOT NULL IDENTITY,
    [CON_DATE_CONSULTATION] datetime2 NOT NULL,
    [CON_NOTES_OBSERVATIONS] nvarchar(max) NULL,
    [CON_PATIENT_ID] int NOT NULL,
    [CON_DENTISTE_ID] int NOT NULL,
    CONSTRAINT [PK_CONSULTATION] PRIMARY KEY ([CON_ID]),
    CONSTRAINT [FK_CONSULTATION_PATIENT_CON_PATIENT_ID] FOREIGN KEY ([CON_PATIENT_ID]) REFERENCES [PATIENT] ([PAT_ID]) ON DELETE NO ACTION,
    CONSTRAINT [FK_CONSULTATION_USER_CON_DENTISTE_ID] FOREIGN KEY ([CON_DENTISTE_ID]) REFERENCES [USER] ([USR_ID]) ON DELETE NO ACTION
);

CREATE TABLE [RENDEZ_VOUS] (
    [RDV_ID] int NOT NULL IDENTITY,
    [RDV_DATE_HEURE] datetime2 NOT NULL,
    [RDV_DUREE_ESTIMEE] time NOT NULL,
    [RDV_STATUT] nvarchar(30) NOT NULL,
    [RDV_MOTIF] nvarchar(max) NULL,
    [RDV_NOTE] nvarchar(max) NULL,
    [RDV_PATIENT_ID] int NOT NULL,
    [RDV_DENTISTE_ID] int NOT NULL,
    CONSTRAINT [PK_RENDEZ_VOUS] PRIMARY KEY ([RDV_ID]),
    CONSTRAINT [FK_RENDEZ_VOUS_PATIENT_RDV_PATIENT_ID] FOREIGN KEY ([RDV_PATIENT_ID]) REFERENCES [PATIENT] ([PAT_ID]) ON DELETE NO ACTION,
    CONSTRAINT [FK_RENDEZ_VOUS_USER_RDV_DENTISTE_ID] FOREIGN KEY ([RDV_DENTISTE_ID]) REFERENCES [USER] ([USR_ID]) ON DELETE NO ACTION
);

CREATE TABLE [ORDONNANCE] (
    [ORD_ID] int NOT NULL IDENTITY,
    [ORD_DATE_EMISSION] datetime2 NOT NULL,
    [ORD_TRAITEMENT] nvarchar(max) NOT NULL,
    [ORD_CONSULTATION_ID] int NOT NULL,
    CONSTRAINT [PK_ORDONNANCE] PRIMARY KEY ([ORD_ID]),
    CONSTRAINT [FK_ORDONNANCE_CONSULTATION_ORD_CONSULTATION_ID] FOREIGN KEY ([ORD_CONSULTATION_ID]) REFERENCES [CONSULTATION] ([CON_ID]) ON DELETE CASCADE
);

CREATE TABLE [SOIN_EFFECTUE] (
    [SOI_ID] int NOT NULL IDENTITY,
    [SOI_NUMERO_DENT] int NULL,
    [SOI_FACE_DENTAIRE] nvarchar(50) NULL,
    [SOI_PRIX_APPLIQUE] decimal(18,2) NOT NULL,
    [SOI_NOTES] nvarchar(max) NULL,
    [SOI_CONSULTATION_ID] int NOT NULL,
    [SOI_ACTE_MEDICAL_ID] int NOT NULL,
    CONSTRAINT [PK_SOIN_EFFECTUE] PRIMARY KEY ([SOI_ID]),
    CONSTRAINT [FK_SOIN_EFFECTUE_ACTE_MEDICAL_SOI_ACTE_MEDICAL_ID] FOREIGN KEY ([SOI_ACTE_MEDICAL_ID]) REFERENCES [ACTE_MEDICAL] ([ACT_ID]) ON DELETE NO ACTION,
    CONSTRAINT [FK_SOIN_EFFECTUE_CONSULTATION_SOI_CONSULTATION_ID] FOREIGN KEY ([SOI_CONSULTATION_ID]) REFERENCES [CONSULTATION] ([CON_ID]) ON DELETE CASCADE
);

CREATE INDEX [IX_AUDIT_LOG_AUD_TABLE_NAME] ON [AUDIT_LOG] ([AUD_TABLE_NAME]);

CREATE INDEX [IX_AUDIT_LOG_AUD_TIMESTAMP] ON [AUDIT_LOG] ([AUD_TIMESTAMP]);

CREATE INDEX [IX_CONSULTATION_CON_DENTISTE_ID] ON [CONSULTATION] ([CON_DENTISTE_ID]);

CREATE INDEX [IX_CONSULTATION_CON_PATIENT_ID] ON [CONSULTATION] ([CON_PATIENT_ID]);

CREATE UNIQUE INDEX [IX_FACTURE_FAC_NUMERO_FACTURE] ON [FACTURE] ([FAC_NUMERO_FACTURE]);

CREATE INDEX [IX_FACTURE_FAC_PATIENT_ID] ON [FACTURE] ([FAC_PATIENT_ID]);

CREATE UNIQUE INDEX [IX_ORDONNANCE_ORD_CONSULTATION_ID] ON [ORDONNANCE] ([ORD_CONSULTATION_ID]);

CREATE INDEX [IX_PAIEMENT_PAI_FACTURE_ID] ON [PAIEMENT] ([PAI_FACTURE_ID]);

CREATE INDEX [IX_RENDEZ_VOUS_RDV_DENTISTE_ID] ON [RENDEZ_VOUS] ([RDV_DENTISTE_ID]);

CREATE INDEX [IX_RENDEZ_VOUS_RDV_PATIENT_ID] ON [RENDEZ_VOUS] ([RDV_PATIENT_ID]);

CREATE INDEX [IX_SOIN_EFFECTUE_SOI_ACTE_MEDICAL_ID] ON [SOIN_EFFECTUE] ([SOI_ACTE_MEDICAL_ID]);

CREATE INDEX [IX_SOIN_EFFECTUE_SOI_CONSULTATION_ID] ON [SOIN_EFFECTUE] ([SOI_CONSULTATION_ID]);

CREATE UNIQUE INDEX [IX_USER_USR_EMAIL] ON [USER] ([USR_EMAIL]);

CREATE INDEX [IX_USER_USR_ROLE_ID] ON [USER] ([USR_ROLE_ID]);

CREATE UNIQUE INDEX [IX_USER_USR_USERNAME] ON [USER] ([USR_USERNAME]);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260606142505_v001', N'10.0.0');

COMMIT;
GO

BEGIN TRANSACTION;
CREATE TABLE [ARTICLE] (
    [ART_ID] int NOT NULL IDENTITY,
    [ART_NOM] nvarchar(100) NOT NULL,
    [ART_DESCRIPTION] nvarchar(max) NULL,
    [ART_QUANTITE_EN_STOCK] int NOT NULL,
    [ART_SEUIL_ALERTE] int NOT NULL,
    [ART_UNITE] nvarchar(50) NOT NULL,
    CONSTRAINT [PK_ARTICLE] PRIMARY KEY ([ART_ID])
);

CREATE TABLE [RECETTE_ACTE] (
    [REC_ID] int NOT NULL IDENTITY,
    [REC_QUANTITE_REQUISE] int NOT NULL,
    [REC_ACTE_MEDICAL_ID] int NOT NULL,
    [REC_ARTICLE_ID] int NOT NULL,
    CONSTRAINT [PK_RECETTE_ACTE] PRIMARY KEY ([REC_ID]),
    CONSTRAINT [FK_RECETTE_ACTE_ACTE_MEDICAL_REC_ACTE_MEDICAL_ID] FOREIGN KEY ([REC_ACTE_MEDICAL_ID]) REFERENCES [ACTE_MEDICAL] ([ACT_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_RECETTE_ACTE_ARTICLE_REC_ARTICLE_ID] FOREIGN KEY ([REC_ARTICLE_ID]) REFERENCES [ARTICLE] ([ART_ID]) ON DELETE CASCADE
);

CREATE INDEX [IX_RECETTE_ACTE_REC_ACTE_MEDICAL_ID] ON [RECETTE_ACTE] ([REC_ACTE_MEDICAL_ID]);

CREATE INDEX [IX_RECETTE_ACTE_REC_ARTICLE_ID] ON [RECETTE_ACTE] ([REC_ARTICLE_ID]);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260613110114_v002', N'10.0.0');

COMMIT;
GO

BEGIN TRANSACTION;
CREATE TABLE [NOTIFICATION] (
    [NTF_ID] int NOT NULL IDENTITY,
    [NTF_NATURE] int NOT NULL,
    [NTF_ENTITY_ID] int NOT NULL,
    [NTF_ENTITY_CODE] nvarchar(max) NOT NULL,
    [NTF_TITLE] nvarchar(max) NOT NULL,
    [NTF_NOTE] nvarchar(max) NOT NULL,
    [NO_DOMAINE] int NOT NULL,
    [USR_ID_CREATED_BY] int NOT NULL,
    [USR_ID_CREATED_TO] int NOT NULL,
    [NTF_DATE] datetime2 NOT NULL,
    [NTF_SEEN] bit NOT NULL,
    [NTF_TYPE] int NOT NULL,
    [NTF_DEMANDE_ID] int NOT NULL,
    CONSTRAINT [PK_NOTIFICATION] PRIMARY KEY ([NTF_ID]),
    CONSTRAINT [FK_NOTIFICATION_USER_USR_ID_CREATED_BY] FOREIGN KEY ([USR_ID_CREATED_BY]) REFERENCES [USER] ([USR_ID]) ON DELETE NO ACTION,
    CONSTRAINT [FK_NOTIFICATION_USER_USR_ID_CREATED_TO] FOREIGN KEY ([USR_ID_CREATED_TO]) REFERENCES [USER] ([USR_ID]) ON DELETE NO ACTION
);

CREATE INDEX [IX_NOTIFICATION_USR_ID_CREATED_BY] ON [NOTIFICATION] ([USR_ID_CREATED_BY]);

CREATE INDEX [IX_NOTIFICATION_USR_ID_CREATED_TO] ON [NOTIFICATION] ([USR_ID_CREATED_TO]);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260613143001_v003', N'10.0.0');

COMMIT;
GO

BEGIN TRANSACTION;
CREATE TABLE [OPTION] (
    [OPT_ID] int NOT NULL IDENTITY,
    [OPT_NAME] nvarchar(256) NOT NULL,
    [OPT_VALUE] nvarchar(1024) NOT NULL,
    [OPT_REQUIRED] bit NOT NULL,
    [OPT_DESCRIPTION] nvarchar(512) NOT NULL,
    [OPT_LABEL] nvarchar(256) NOT NULL,
    [OPT_GROUP] nvarchar(100) NOT NULL,
    CONSTRAINT [PK_OPTION] PRIMARY KEY ([OPT_ID])
);

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'OPT_ID', N'OPT_DESCRIPTION', N'OPT_GROUP', N'OPT_LABEL', N'OPT_NAME', N'OPT_REQUIRED', N'OPT_VALUE') AND [object_id] = OBJECT_ID(N'[OPTION]'))
    SET IDENTITY_INSERT [OPTION] ON;
INSERT INTO [OPTION] ([OPT_ID], [OPT_DESCRIPTION], [OPT_GROUP], [OPT_LABEL], [OPT_NAME], [OPT_REQUIRED], [OPT_VALUE])
VALUES (1, N'Serveur SMTP sortant', N'SMTP', N'Hôte SMTP', N'smtp.host', CAST(1 AS bit), N'smtp.gmail.com'),
(2, N'Port de connexion SMTP (587 TLS, 465 SSL)', N'SMTP', N'Port SMTP', N'smtp.port', CAST(1 AS bit), N'587'),
(3, N'Adresse email de l''expéditeur', N'SMTP', N'Email expéditeur', N'smtp.username', CAST(1 AS bit), N''),
(4, N'Mot de passe ou app password', N'SMTP', N'Mot de passe', N'smtp.password', CAST(0 AS bit), N''),
(5, N'Chiffrement de la connexion', N'SMTP', N'Activer SSL/TLS', N'smtp.ssl', CAST(1 AS bit), N'true'),
(6, N'Nom du compte Cloudinary', N'Cloudinary', N'Cloud Name', N'cloudinary.name', CAST(0 AS bit), N''),
(7, N'Clé API Cloudinary', N'Cloudinary', N'API Key', N'cloudinary.key', CAST(0 AS bit), N''),
(8, N'Clé secrète Cloudinary', N'Cloudinary', N'API Secret', N'cloudinary.secret', CAST(0 AS bit), N''),
(9, N'Dossier racine pour les fichiers', N'Cloudinary', N'Dossier', N'cloudinary.folder', CAST(0 AS bit), N'dentiste'),
(10, N'Local, Desactiver, Google, Microsoft', N'Storage', N'Type de stockage', N'storage.provider.type', CAST(1 AS bit), N'Desactiver'),
(11, N'Token d''authentification cloud', N'Storage', N'Token OAuth', N'storage.provider.token', CAST(0 AS bit), N''),
(12, N'Chemin absolu du répertoire de stockage local', N'Storage', N'Chemin local', N'storage.provider.path', CAST(0 AS bit), N''),
(13, N'Email du compte cloud connecté', N'Storage', N'Compte connecté', N'storage.provider.account', CAST(0 AS bit), N'');
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'OPT_ID', N'OPT_DESCRIPTION', N'OPT_GROUP', N'OPT_LABEL', N'OPT_NAME', N'OPT_REQUIRED', N'OPT_VALUE') AND [object_id] = OBJECT_ID(N'[OPTION]'))
    SET IDENTITY_INSERT [OPTION] OFF;

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20260613171024_v004', N'10.0.0');

COMMIT;
GO

