// <auto-generated />
using System;
using Dentiste.Data.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dentiste.Data.Migrations
{
    [DbContext(typeof(DentisteContext))]
    partial class DentisteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dentiste.Data.Models.ActeMedicalDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ACT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("ACT_CABINET_ID");

                    b.Property<string>("CodeNomenclature")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACT_CODE_NOMENCLATURE");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ACT_LIBELLE");

                    b.Property<decimal>("TarifDeBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ACT_TARIF_DE_BASE");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.ToTable("ACTE_MEDICAL");
                });

            modelBuilder.Entity("Dentiste.Data.Models.ArticleDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ART_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("ART_CABINET_ID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ART_DESCRIPTION");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ART_NOM");

                    b.Property<int>("QuantiteEnStock")
                        .HasColumnType("int")
                        .HasColumnName("ART_QUANTITE_EN_STOCK");

                    b.Property<int>("SeuilAlerte")
                        .HasColumnType("int")
                        .HasColumnName("ART_SEUIL_ALERTE");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ART_UNITE");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.ToTable("ARTICLE");
                });

            modelBuilder.Entity("Dentiste.Data.Models.AuditLogDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AUD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AUD_ACTION");

                    b.Property<int?>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("AUD_CABINET_ID");

                    b.Property<string>("KeyValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUD_KEY_VALUES");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUD_NEW_VALUES");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUD_OLD_VALUES");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AUD_TABLE_NAME");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("AUD_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AUD_USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("TableName");

                    b.HasIndex("Timestamp");

                    b.ToTable("AUDIT_LOG");
                });

            modelBuilder.Entity("Dentiste.Data.Models.CabinetDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CAB_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CAB_ADRESSE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CAB_CREATED_AT");

                    b.Property<bool>("IsSubscriptionActive")
                        .HasColumnType("bit")
                        .HasColumnName("CAB_IS_ACTIVE");

                    b.Property<string>("NomCabinet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CAB_NOM");

                    b.Property<string>("TelephoneCorporate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CAB_TELEPHONE");

                    b.HasKey("Id");

                    b.ToTable("CABINET");
                });

            modelBuilder.Entity("Dentiste.Data.Models.ConfigurationCabinetDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CFG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("CFG_CABINET_ID");

                    b.Property<string>("SenderName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CFG_SENDER_NAME");

                    b.Property<bool?>("SmtpEnableSsl")
                        .HasColumnType("bit")
                        .HasColumnName("CFG_SMTP_SSL");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CFG_SMTP_HOST");

                    b.Property<string>("SmtpPassword")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CFG_SMTP_PASSWORD");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("int")
                        .HasColumnName("CFG_SMTP_PORT");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CFG_SMTP_USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId")
                        .IsUnique();

                    b.ToTable("CONFIGURATION_CABINET");
                });

            modelBuilder.Entity("Dentiste.Data.Models.ConsultationDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CON_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("CON_CABINET_ID");

                    b.Property<DateTime>("DateConsultation")
                        .HasColumnType("datetime2")
                        .HasColumnName("CON_DATE_CONSULTATION");

                    b.Property<int>("DentisteId")
                        .HasColumnType("int")
                        .HasColumnName("CON_DENTISTE_ID");

                    b.Property<string>("NotesObservations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CON_NOTES_OBSERVATIONS");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("CON_PATIENT_ID");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("DentisteId");

                    b.HasIndex("PatientId");

                    b.ToTable("CONSULTATION");
                });

            modelBuilder.Entity("Dentiste.Data.Models.FactureDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FAC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("FAC_CABINET_ID");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2")
                        .HasColumnName("FAC_DATE_EMISSION");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FAC_MONTANT_PAYE");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FAC_MONTANT_TOTAL");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FAC_NUMERO_FACTURE");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("FAC_PATIENT_ID");

                    b.Property<string>("StatutPaiement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("FAC_STATUT_PAIEMENT");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("NumeroFacture")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("FACTURE");
                });

            modelBuilder.Entity("Dentiste.Data.Models.NotificationDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NTF_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("NTF_CABINET_ID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("USR_ID_CREATED_BY");

                    b.Property<int>("CreatedTo")
                        .HasColumnType("int")
                        .HasColumnName("USR_ID_CREATED_TO");

                    b.Property<DateTime>("DateRappel")
                        .HasColumnType("datetime2")
                        .HasColumnName("NTF_DATE");

                    b.Property<int>("DemandeId")
                        .HasColumnType("int")
                        .HasColumnName("NTF_DEMANDE_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NTF_NOTE");

                    b.Property<int>("Domaine")
                        .HasColumnType("int")
                        .HasColumnName("NO_DOMAINE");

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NTF_ENTITY_CODE");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("NTF_ENTITY_ID");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("bit")
                        .HasColumnName("NTF_SEEN");

                    b.Property<int>("Nature")
                        .HasColumnType("int")
                        .HasColumnName("NTF_NATURE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NTF_TITLE");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("NTF_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedTo");

                    b.ToTable("NOTIFICATION");
                });

            modelBuilder.Entity("Dentiste.Data.Models.OptionDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OPT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("OPT_DESCRIPTION");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("OPT_GROUP");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("OPT_LABEL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("OPT_NAME");

                    b.Property<bool>("Required")
                        .HasColumnType("bit")
                        .HasColumnName("OPT_REQUIRED");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("OPT_VALUE");

                    b.HasKey("Id");

                    b.ToTable("OPTION");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Serveur SMTP sortant",
                            Group = "SMTP",
                            Label = "Hôte SMTP",
                            Name = "smtp.host",
                            Required = true,
                            Value = "smtp.gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Port de connexion SMTP (587 TLS, 465 SSL)",
                            Group = "SMTP",
                            Label = "Port SMTP",
                            Name = "smtp.port",
                            Required = true,
                            Value = "587"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Adresse email de l'expéditeur",
                            Group = "SMTP",
                            Label = "Email expéditeur",
                            Name = "smtp.username",
                            Required = true,
                            Value = ""
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mot de passe ou app password",
                            Group = "SMTP",
                            Label = "Mot de passe",
                            Name = "smtp.password",
                            Required = false,
                            Value = ""
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chiffrement de la connexion",
                            Group = "SMTP",
                            Label = "Activer SSL/TLS",
                            Name = "smtp.ssl",
                            Required = true,
                            Value = "true"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Nom du compte Cloudinary",
                            Group = "Cloudinary",
                            Label = "Cloud Name",
                            Name = "cloudinary.name",
                            Required = false,
                            Value = ""
                        },
                        new
                        {
                            Id = 7,
                            Description = "Clé API Cloudinary",
                            Group = "Cloudinary",
                            Label = "API Key",
                            Name = "cloudinary.key",
                            Required = false,
                            Value = ""
                        },
                        new
                        {
                            Id = 8,
                            Description = "Clé secrète Cloudinary",
                            Group = "Cloudinary",
                            Label = "API Secret",
                            Name = "cloudinary.secret",
                            Required = false,
                            Value = ""
                        },
                        new
                        {
                            Id = 9,
                            Description = "Dossier racine pour les fichiers",
                            Group = "Cloudinary",
                            Label = "Dossier",
                            Name = "cloudinary.folder",
                            Required = false,
                            Value = "dentiste"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Local, Desactiver, Google, Microsoft",
                            Group = "Storage",
                            Label = "Type de stockage",
                            Name = "storage.provider.type",
                            Required = true,
                            Value = "Desactiver"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Token d'authentification cloud",
                            Group = "Storage",
                            Label = "Token OAuth",
                            Name = "storage.provider.token",
                            Required = false,
                            Value = ""
                        },
                        new
                        {
                            Id = 12,
                            Description = "Chemin absolu du répertoire de stockage local",
                            Group = "Storage",
                            Label = "Chemin local",
                            Name = "storage.provider.path",
                            Required = false,
                            Value = ""
                        },
                        new
                        {
                            Id = 13,
                            Description = "Email du compte cloud connecté",
                            Group = "Storage",
                            Label = "Compte connecté",
                            Name = "storage.provider.account",
                            Required = false,
                            Value = ""
                        });
                });

            modelBuilder.Entity("Dentiste.Data.Models.OrdonnanceDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ORD_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("ORD_CABINET_ID");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int")
                        .HasColumnName("ORD_CONSULTATION_ID");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2")
                        .HasColumnName("ORD_DATE_EMISSION");

                    b.Property<string>("Traitement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ORD_TRAITEMENT");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.ToTable("ORDONNANCE");
                });

            modelBuilder.Entity("Dentiste.Data.Models.PaiementDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAI_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("PAI_CABINET_ID");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAI_DATE_PAIEMENT");

                    b.Property<int>("FactureId")
                        .HasColumnType("int")
                        .HasColumnName("PAI_FACTURE_ID");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("PAI_MODE_PAIEMENT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PAI_MONTANT");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("FactureId");

                    b.ToTable("PAIEMENT");
                });

            modelBuilder.Entity("Dentiste.Data.Models.PatientDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PAT_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAT_ADRESSE");

                    b.Property<string>("AntecedentsMedicaux")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAT_ANTECEDENTS_MEDICAUX");

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("PAT_CABINET_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAT_CREATED_AT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAT_DATE_NAISSANCE");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAT_EMAIL");

                    b.Property<string>("GroupSanguin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAT_GROUP_SANGUIN");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PAT_NOM");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PAT_PRENOM");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PAT_TELEPHONE");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.ToTable("PATIENT");
                });

            modelBuilder.Entity("Dentiste.Data.Models.RecetteActeDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("REC_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActeMedicalId")
                        .HasColumnType("int")
                        .HasColumnName("REC_ACTE_MEDICAL_ID");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("REC_ARTICLE_ID");

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("REC_CABINET_ID");

                    b.Property<int>("QuantiteRequise")
                        .HasColumnType("int")
                        .HasColumnName("REC_QUANTITE_REQUISE");

                    b.HasKey("Id");

                    b.HasIndex("ActeMedicalId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CabinetId");

                    b.ToTable("RECETTE_ACTE");
                });

            modelBuilder.Entity("Dentiste.Data.Models.RendezVousDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RDV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("RDV_CABINET_ID");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2")
                        .HasColumnName("RDV_DATE_HEURE");

                    b.Property<int>("DentisteId")
                        .HasColumnType("int")
                        .HasColumnName("RDV_DENTISTE_ID");

                    b.Property<TimeSpan>("DureeEstimee")
                        .HasColumnType("time")
                        .HasColumnName("RDV_DUREE_ESTIMEE");

                    b.Property<string>("Motif")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RDV_MOTIF");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RDV_NOTE");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("RDV_PATIENT_ID");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("RDV_STATUT");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("DentisteId");

                    b.HasIndex("PatientId");

                    b.ToTable("RENDEZ_VOUS");
                });

            modelBuilder.Entity("Dentiste.Data.Models.RoleDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ROL_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROL_DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ROL_NAME");

                    b.HasKey("Id");

                    b.ToTable("ROLE");
                });

            modelBuilder.Entity("Dentiste.Data.Models.SoinEffectueDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SOI_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActeMedicalId")
                        .HasColumnType("int")
                        .HasColumnName("SOI_ACTE_MEDICAL_ID");

                    b.Property<int>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("SOI_CABINET_ID");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int")
                        .HasColumnName("SOI_CONSULTATION_ID");

                    b.Property<string>("FaceDentaire")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SOI_FACE_DENTAIRE");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SOI_NOTES");

                    b.Property<int?>("NumeroDent")
                        .HasColumnType("int")
                        .HasColumnName("SOI_NUMERO_DENT");

                    b.Property<decimal>("PrixApplique")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SOI_PRIX_APPLIQUE");

                    b.HasKey("Id");

                    b.HasIndex("ActeMedicalId");

                    b.HasIndex("CabinetId");

                    b.HasIndex("ConsultationId");

                    b.ToTable("SOIN_EFFECTUE");
                });

            modelBuilder.Entity("Dentiste.Data.Models.UserDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USR_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CabinetId")
                        .HasColumnType("int")
                        .HasColumnName("USR_CABINET_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("USR_CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USR_EMAIL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("USR_IS_ACTIVE");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USR_NOM");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("USR_PASSWORD_HASH");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("USR_PASSWORD_SALT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("USR_PRENOM");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("USR_ROLE_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USR_USERNAME");

                    b.HasKey("Id");

                    b.HasIndex("CabinetId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USER");
                });

            modelBuilder.Entity("Dentiste.Data.Models.ActeMedicalDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Dentiste.Data.Models.ArticleDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Dentiste.Data.Models.AuditLogDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Dentiste.Data.Models.ConfigurationCabinetDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithOne()
                        .HasForeignKey("Dentiste.Data.Models.ConfigurationCabinetDao", "CabinetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Dentiste.Data.Models.ConsultationDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.UserDao", "Dentiste")
                        .WithMany()
                        .HasForeignKey("DentisteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.PatientDao", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Dentiste");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dentiste.Data.Models.FactureDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.PatientDao", "Patient")
                        .WithMany("Factures")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dentiste.Data.Models.NotificationDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.UserDao", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.UserDao", "CreatedToUser")
                        .WithMany()
                        .HasForeignKey("CreatedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("CreatedByUser");

                    b.Navigation("CreatedToUser");
                });

            modelBuilder.Entity("Dentiste.Data.Models.OrdonnanceDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.ConsultationDao", "Consultation")
                        .WithOne("Ordonnance")
                        .HasForeignKey("Dentiste.Data.Models.OrdonnanceDao", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Dentiste.Data.Models.PaiementDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.FactureDao", "Facture")
                        .WithMany("Paiements")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("Dentiste.Data.Models.PatientDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Dentiste.Data.Models.RecetteActeDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.ActeMedicalDao", "ActeMedical")
                        .WithMany()
                        .HasForeignKey("ActeMedicalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.ArticleDao", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActeMedical");

                    b.Navigation("Article");

                    b.Navigation("Cabinet");
                });

            modelBuilder.Entity("Dentiste.Data.Models.RendezVousDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.UserDao", "Dentiste")
                        .WithMany()
                        .HasForeignKey("DentisteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.PatientDao", "Patient")
                        .WithMany("RendezVous")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Dentiste");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dentiste.Data.Models.SoinEffectueDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.ActeMedicalDao", "ActeMedical")
                        .WithMany()
                        .HasForeignKey("ActeMedicalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany()
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dentiste.Data.Models.ConsultationDao", "Consultation")
                        .WithMany("SoinsEffectues")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActeMedical");

                    b.Navigation("Cabinet");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Dentiste.Data.Models.UserDao", b =>
                {
                    b.HasOne("Dentiste.Data.Models.CabinetDao", "Cabinet")
                        .WithMany("Users")
                        .HasForeignKey("CabinetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dentiste.Data.Models.RoleDao", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabinet");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Dentiste.Data.Models.CabinetDao", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Dentiste.Data.Models.ConsultationDao", b =>
                {
                    b.Navigation("Ordonnance");

                    b.Navigation("SoinsEffectues");
                });

            modelBuilder.Entity("Dentiste.Data.Models.FactureDao", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("Dentiste.Data.Models.PatientDao", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("Factures");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("Dentiste.Data.Models.RoleDao", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
